apiVersion: v1
kind: Service
metadata:
  name: talos
  namespace: talos
spec:
  selector:
    app: talos
  ports:
    - name: http
      port: 3000
      targetPort: 3000
      protocol: TCP
    - name: metrics
      port: 9464
      targetPort: 9464
      protocol: TCP
