---
extends: default

rules:
  line-length:
    max: 120
    level: warning
  truthy:
    allowed-values: ['true', 'false', 'yes', 'no']
  comments:
    min-spaces-from-content: 1
  braces:
    min-spaces-inside: 0
    max-spaces-inside: 1
  brackets:
    min-spaces-inside: 0
    max-spaces-inside: 0
  indentation:
    spaces: 2
    indent-sequences: consistent
  # Required for ansible-lint compatibility
  comments-indentation: false
  octal-values:
    forbid-implicit-octal: true
    forbid-explicit-octal: true

ignore:
  - .venv/
  - pulumi/.venv/
  # Third-party k8s manifest with non-standard formatting
  - argocd/manifests/tailscale-operator-base/operator.yaml
