apiVersion: tailscale.com/v1alpha1
kind: ProxyClass
metadata:
  name: default
spec:
  statefulSet:
    pod:
      tailscaleContainer:
        image: registry.ops.eblu.me/blumeops/tailscale:v1.94.2-d03ed33
      tailscaleInitContainer:
        image: registry.ops.eblu.me/blumeops/tailscale:v1.94.2-d03ed33
