---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kiwix
resources:
  - deployment.yaml
  - service.yaml
  - ingress-tailscale.yaml
  - cronjob-zim-watcher.yaml

images:
  - name: registry.ops.eblu.me/blumeops/kiwix-serve
    newTag: v3.8.2-f386e2e-nix
  - name: registry.ops.eblu.me/blumeops/transmission
    newTag: v4.1.1-f386e2e-nix
  - name: registry.ops.eblu.me/blumeops/kubectl
    newTag: v1.34.3-f386e2e-nix

configMapGenerator:
  - name: kiwix-zim-torrents
    files:
      - torrents.txt
  - name: zim-torrent-sync-script
    files:
      - sync-zim-torrents.sh
