---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: immich
resources:
  - deployment-server.yaml
  - deployment-ml.yaml
  - deployment-valkey.yaml
  - service.yaml
  - service-ml.yaml
  - service-valkey.yaml
  - pvc-ml-cache.yaml
  - pv-nfs.yaml
  - pvc.yaml
  - ingress-tailscale.yaml
images:
  - name: ghcr.io/immich-app/immich-server
    newTag: v2.6.3
  - name: ghcr.io/immich-app/immich-machine-learning
    newTag: v2.6.3
  - name: docker.io/valkey/valkey
    newName: registry.ops.eblu.me/blumeops/valkey
    newTag: v8.1.6-r0-946fa75
