# Immich database password secret
# Apply with: op inject -i argocd/manifests/immich/secret-db.yaml.tpl | kubectl apply -f -
apiVersion: v1
kind: Secret
metadata:
  name: immich-db
  namespace: immich
type: Opaque
stringData:
  # Password is auto-generated by CloudNativePG and stored in immich-pg-app secret
  # Retrieve with: kubectl -n databases get secret immich-pg-app -o jsonpath='{.data.password}' | base64 -d
  password: "{{ op://blumeops/immich-pg/password }}"
