# Nix container build workflow
# Triggers on tags matching: <container>-v<version>
# Builds from containers/<container>/default.nix if it exists, skips otherwise
# Pushes to Zot registry via skopeo with -nix image tag suffix
#
# Examples:
#   nettest-v1.0.0  -> builds containers/nettest/default.nix, pushes :v1.0.0-nix
#   devpi-v2.1.0    -> skips (no default.nix)
name: Build Container (Nix)

on:
  push:
    tags:
      - '*-v[0-9]*'

jobs:
  build:
    runs-on: nix-container-builder
    steps:
      - name: Parse tag
        id: parse
        run: |
          TAG="${GITHUB_REF_NAME}"
          echo "Tag: $TAG"

          # Extract container name (everything before -v)
          # e.g., "nettest-v1.0.0" -> "nettest", "my-app-v2.0.0" -> "my-app"
          CONTAINER="${TAG%-v[0-9]*}"
          VERSION="${TAG#"${CONTAINER}"-}"

          echo "container=$CONTAINER" >> "$GITHUB_OUTPUT"
          echo "version=$VERSION" >> "$GITHUB_OUTPUT"
          echo "Container: $CONTAINER"
          echo "Version: $VERSION"

      - name: Checkout
        uses: actions/checkout@v4

      - name: Check if nix container exists
        id: check
        run: |
          CONTAINER="${{ steps.parse.outputs.container }}"
          CONTEXT="containers/$CONTAINER"

          if [ -f "$CONTEXT/default.nix" ]; then
            echo "Found $CONTEXT/default.nix"
            echo "exists=true" >> "$GITHUB_OUTPUT"
          else
            echo "No default.nix found at $CONTEXT/default.nix — skipping"
            echo "exists=false" >> "$GITHUB_OUTPUT"
          fi

      - name: Resolve nixpkgs
        if: steps.check.outputs.exists == 'true'
        id: nixpkgs
        run: |
          # Resolve nixpkgs from the flake registry for <nixpkgs> lookup
          NIXPKGS_PATH=$(nix flake metadata nixpkgs --json | jq -r '.path')
          echo "Resolved nixpkgs: $NIXPKGS_PATH"
          echo "path=$NIXPKGS_PATH" >> "$GITHUB_OUTPUT"

      - name: Build with nix
        if: steps.check.outputs.exists == 'true'
        id: build
        env:
          NIX_PATH: "nixpkgs=${{ steps.nixpkgs.outputs.path }}"
        run: |
          CONTAINER="${{ steps.parse.outputs.container }}"
          echo "Building containers/$CONTAINER/default.nix"
          echo "NIX_PATH=$NIX_PATH"
          nix-build "containers/$CONTAINER/default.nix" -o result
          echo "Build complete: $(readlink result)"

      - name: Push to registry
        if: steps.check.outputs.exists == 'true'
        run: |
          CONTAINER="${{ steps.parse.outputs.container }}"
          VERSION="${{ steps.parse.outputs.version }}"
          IMAGE="registry.ops.eblu.me/blumeops/$CONTAINER:$VERSION-nix"

          echo "Pushing to $IMAGE"
          skopeo copy \
            "docker-archive:result" \
            "docker://$IMAGE"
          echo "Push complete: $IMAGE"
