name: Test CI

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Verify tools
        run: |
          echo "=== Node.js ==="
          node --version
          npm --version
          echo ""
          echo "=== Git ==="
          git --version
          echo ""
          echo "=== Build tools ==="
          make --version 2>&1 | head -1 || true
          gcc --version 2>&1 | head -1 || true
          echo ""
          echo "=== Container tools (Buildah) ==="
          buildah --version
          podman --version
          echo ""
          echo "=== Other tools ==="
          curl --version 2>&1 | head -1 || true
          jq --version

      - name: Show repo info
        run: |
          echo "Repository: ${{ github.repository }}"
          echo "Event: ${{ github.event_name }}"
          echo "Ref: ${{ github.ref }}"
          echo "Branch: ${{ github.ref_name }}"
          echo ""
          echo "=== Files ==="
          ls -la
