---
apiVersion: v1
kind: Service
metadata:
  name: birdnet-go
  namespace: birdnet-go
spec:
  selector:
    app: birdnet-go
  ports:
    - name: http
      port: 8080
      targetPort: 8080
    - name: telemetry
      port: 8090
      targetPort: 8090
