---
# Human-door secrets: the OIDC client secret (shared with authentik via the
# same vault item) and the session-signing key. The 1Password fields keep
# their warrant-* names — same secret material, new consumer — so the
# cutover needs no vault edits. Note what is NOT here: no dispatch
# credential, no vault tokens.
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: horkos-oidc
  namespace: horkos
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-blumeops
  target:
    name: horkos-oidc
    creationPolicy: Owner
  data:
    - secretKey: HORKOS_HUMAN_CLIENT_SECRET
      remoteRef:
        key: "Authentik (blumeops)"
        property: warrant-client-secret
    - secretKey: HORKOS_SESSION_KEY
      remoteRef:
        key: "Authentik (blumeops)"
        property: warrant-session-key
