apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: paperless

resources:
  - deployment.yaml
  - service.yaml
  - pv-nfs.yaml
  - pvc.yaml
  - ingress-tailscale.yaml
  - external-secret.yaml

images:
  - name: registry.ops.eblu.me/blumeops/paperless
    newTag: v2.20.13-07f52e9
  - name: docker.io/library/redis
    newName: registry.ops.eblu.me/blumeops/valkey
    newTag: v8.1.6-r0-946fa75
