---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - serviceaccount.yaml
  - rbac.yaml
  - service.yaml
  - webhook.yaml
  - deployment.yaml
  - cluster-secret-store.yaml

images:
  - name: ghcr.io/external-secrets/external-secrets
    newName: registry.ops.eblu.me/blumeops/external-secrets
    newTag: v2.10.0-55edd40-nix@sha256:c1c5403325b31cb3f52c41a45ff7328e1fb3187c9465527ed822265b2ca2816a
