---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: jobsync
resources:
  - pvc.yaml
  - external-secret.yaml
  - deployment.yaml
  - service.yaml
  - ingress-tailscale.yaml

images:
  - name: blumeops/jobsync
    newName: registry.ops.eblu.me/blumeops/jobsync
    newTag: "v1.1.4-e51ec83-nix"
