---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jobsync-data
  namespace: jobsync
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 5Gi
