---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: prowler

resources:
  - serviceaccount.yaml
  - rbac.yaml
  - pv-nfs.yaml
  - pvc.yaml
  - cronjob.yaml

configMapGenerator:
  - name: prowler-mutelist
    options:
      disableNameSuffixHash: true
    files:
      - mutelist/core-pod-security.yaml
      - mutelist/kubelet-node-files.yaml
      - mutelist/rbac.yaml

images:
  - name: registry.ops.eblu.me/blumeops/prowler
    newTag: v5.39.1-dd1f467-nix@sha256:2faf2051b8911f3b53cfb37c519b3ebc3c8971c9bb69cf4894605e7b65cd9889
