---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: prowler

resources:
  - serviceaccount.yaml
  - rbac.yaml
  - pv-nfs.yaml
  - pvc.yaml
  - cronjob.yaml

configMapGenerator:
  - name: prowler-mutelist
    options:
      disableNameSuffixHash: true
    files:
      - mutelist/core-pod-security.yaml
      - mutelist/rbac.yaml

images:
  - name: registry.ops.eblu.me/blumeops/prowler
    newTag: v5.39.1-9258e39-nix
