apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prowler-reports
  namespace: prowler
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  volumeName: prowler-reports-nfs-pv-ringtail
  resources:
    requests:
      storage: 10Gi
