apiVersion: tailscale.com/v1alpha1
kind: ProxyClass
metadata:
  name: default
spec:
  statefulSet:
    pod:
      tailscaleContainer:
        image: registry.ops.eblu.me/blumeops/tailscale:v1.98.5-585e57e-nix
      tailscaleInitContainer:
        image: registry.ops.eblu.me/blumeops/tailscale:v1.98.5-585e57e-nix
