apiVersion: tailscale.com/v1alpha1
kind: ProxyClass
metadata:
  name: default
spec:
  statefulSet:
    pod:
      tailscaleContainer:
        image: registry.ops.eblu.me/blumeops/tailscale:v1.102.5-7f39ab6-nix
      tailscaleInitContainer:
        image: registry.ops.eblu.me/blumeops/tailscale:v1.102.5-7f39ab6-nix
