---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: warrant
resources:
  - deployment.yaml
  - pvc.yaml
  - service.yaml
  - ingress-tailscale.yaml
  - external-secret-oidc.yaml
  - external-secret-dispatch.yaml
images:
  - name: registry.ops.eblu.me/blumeops/warrant
    newTag: v0.3.3-d311145-nix
