apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
  # Pin to specific version for intentional upgrades
  # ArgoCD v3.3.6
  - https://raw.githubusercontent.com/argoproj/argo-cd/998fb59dc355653c0657908a6ea2f87136e022d1/manifests/install.yaml
  - ingress-tailscale.yaml
  - external-secret-repo-forge.yaml

patches:
  - path: argocd-cmd-params-cm.yaml
  - path: argocd-ssh-known-hosts-cm.yaml
  - path: argocd-cm-patch.yaml
  - path: argocd-rbac-cm-patch.yaml
  - path: argocd-resources-patch.yaml
