apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: monitoring

resources:
  - serviceaccount.yaml
  - pvc.yaml
  - deployment.yaml
  - service.yaml
  - rbac.yaml

images:
  - name: docker.io/library/alpine
    newTag: "3.21"
  - name: docker.io/library/busybox
    newTag: 1.31.1
  - name: registry.ops.eblu.me/blumeops/grafana-sidecar
    newTag: v2.6.0-61fcd5d
  - name: registry.ops.eblu.me/blumeops/grafana
    newTag: v12.4.2-4c54774

configMapGenerator:
  - name: grafana
    files:
      - grafana.ini
      - datasources.yaml
      - alerting.yaml
    options:
      labels:
        app.kubernetes.io/name: grafana
        app.kubernetes.io/instance: grafana
  - name: grafana-config-dashboards
    files:
      - provider.yaml
    options:
      labels:
        app.kubernetes.io/name: grafana
        app.kubernetes.io/instance: grafana
