apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: pulumi-access-token
  namespace: pulumi-stack-backup
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-blumeops
  target:
    name: pulumi-access-token
    creationPolicy: Owner
  data:
    - secretKey: token
      remoteRef:
        key: Pulumi
        property: access-token
