apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pulumi-stack-backup
  namespace: pulumi-stack-backup
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
