apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: teslamate

resources:
  - deployment.yaml
  - service.yaml
  - ingress-tailscale.yaml
  - external-secret-db.yaml
  - external-secret-encryption-key.yaml

images:
  - name: registry.ops.eblu.me/blumeops/teslamate
    newTag: v4.2.0-ca01fce-nix@sha256:4b391131fc229b7fc1788a264903b1e7bdb6f382a4c10b961a69bf6641d85b76
