apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: monitoring

resources:
  - statefulset.yaml
  - service.yaml
  - ingress-tailscale.yaml

images:
  - name: grafana/loki
    newName: registry.ops.eblu.me/blumeops/loki
    newTag: v3.7.8-69f4612-nix@sha256:ab8dd2d4f9cff022e6abb2584a1b62d3b1c5cc92e39ad2f3d87b8bdfff8cea8a

configMapGenerator:
  - name: loki-config
    files:
      - loki-config.yaml
