---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mealie-secrets
  namespace: mealie
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-blumeops
  target:
    name: mealie-secrets
    creationPolicy: Owner
  data:
    - secretKey: oidc-client-secret
      remoteRef:
        key: "Authentik (blumeops)"
        property: mealie-client-secret
    - secretKey: openai-api-key
      remoteRef:
        key: "openai (blumeops)"
        property: credential
