apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: mealie

resources:
  - deployment.yaml
  - service.yaml
  - pvc.yaml
  - ingress-tailscale.yaml
  - external-secret.yaml

images:
  - name: registry.ops.eblu.me/blumeops/mealie
    newTag: v3.16.0-22cfd86-nix
