[prometheus]
  http_listen = "0.0.0.0:9130"
  report_errors = true

[influxdb]
  disable = true

[unifi]
  dynamic = false

[unifi.defaults]
  # API key comes from environment variable: UP_UNIFI_DEFAULT_API_KEY
  url = "https://192.168.1.1"
  verify_ssl = false
  save_sites = true
  save_dpi = false
