# External Secrets Operator - Kubernetes secret sync from external providers
# Syncs secrets from 1Password Connect to native Kubernetes Secrets
#
# Chart mirrored from https://github.com/external-secrets/external-secrets
#
# Prerequisites:
# - 1password-connect must be deployed and healthy
#
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: ssh://forgejo@forge.ops.eblu.me:2222/mirrors/external-secrets.git
      targetRevision: helm-chart-2.0.0
      path: deploy/charts/external-secrets
      helm:
        releaseName: external-secrets
        valueFiles:
          - $values/argocd/manifests/external-secrets/values.yaml
    - repoURL: ssh://forgejo@forge.ops.eblu.me:2222/eblume/blumeops.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: external-secrets
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
