# External Secrets Operator for ringtail k3s cluster
# Same chart/values as indri, different destination
#
# Prerequisites:
# - 1password-connect-ringtail must be deployed and healthy
# - external-secrets-crds-ringtail must be synced first
#
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets-ringtail
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: ssh://forgejo@forge.ops.eblu.me:2222/mirrors/external-secrets.git
      targetRevision: helm-chart-2.0.0
      path: deploy/charts/external-secrets
      helm:
        releaseName: external-secrets
        valueFiles:
          - $values/argocd/manifests/external-secrets/values.yaml
    - repoURL: ssh://forgejo@forge.ops.eblu.me:2222/eblume/blumeops.git
      targetRevision: main
      ref: values
  destination:
    server: https://ringtail.tail8d86e.ts.net:6443
    namespace: external-secrets
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
