# Homepage - Service Dashboard / Start Page
#
# Custom container built from gethomepage/homepage, kustomize manifests.
# Dashboard at go.ops.eblu.me / go.tail8d86e.ts.net
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: homepage
  namespace: argocd
spec:
  project: default
  source:
    repoURL: ssh://forgejo@forge.ops.eblu.me:2222/eblume/blumeops.git
    targetRevision: main
    path: argocd/manifests/homepage
  destination:
    server: https://kubernetes.default.svc
    namespace: homepage
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
