---
- name: Restart heph
  ansible.builtin.shell: |
    launchctl unload ~/Library/LaunchAgents/mcquack.eblume.heph.plist 2>/dev/null || true
    launchctl load ~/Library/LaunchAgents/mcquack.eblume.heph.plist
  changed_when: true
