apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: agent-ws

resources:
  - serviceaccount.yaml
  - external-secret-op-token.yaml
  - external-secret-ts-authkey.yaml
  - pvc.yaml
  - networkpolicy.yaml
  - deployment.yaml

images:
  - name: registry.ops.eblu.me/blumeops/agent-ws
    newTag: v0.11.0-76321a0-nix
