---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ollama-models
  namespace: ollama
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  volumeName: ollama-models-pv
  resources:
    requests:
      storage: 200Gi
